Repository thomas-mauran/chess-tui, pull requests merged in 2023-12, with the labels that each got.

#16 fix: remove explicitly set background on board blocks
  examples/demo.gif
  src/ui.rs
Labels: enhancement

#29 feat: helper video demo + readme setup for features + render script
  README.md
  examples/demo.gif
  examples/demo.tape
  examples/helper.gif
  examples/helper.tape
  render_demos.sh
Labels: enhancement

#37 fix: line 8 for history
  Cargo.toml
  src/utils.rs
Labels: bug

#40 docs: add contributing.md
  CONTRIBUTING.md
Labels: documentation

#47 feat: home menu + credit + small fixes
  Cargo.lock
  Cargo.toml
  examples/demo.gif
  examples/demo.tape
  examples/helper.gif
  examples/helper.tape
  src/app.rs
  src/board.rs
  src/constants.rs
  src/handler.rs
  src/lib.rs
  src/popups.rs
  src/ui.rs
Labels: enhancement
