Repository thomas-mauran/chess-tui, pull requests merged in 2024-11, with the labels that each got.

#88 Feat/turn board
  README.md
  examples/demo-two-player.gif
  examples/demo-two-player.tape
  examples/demo.gif
  examples/demo.tape
  examples/helper.gif
  examples/helper.tape
  examples/play_against_black_bot.gif
  examples/play_against_black_bot.tape
  examples/play_against_bot.gif
  examples/play_against_bot.tape
  examples/play_against_white_bot.gif
  examples/play_against_white_bot.tape
  src/app.rs
  src/board.rs
  src/constants.rs
  src/handler.rs
  src/pieces/king.rs
  src/pieces/mod.rs
  src/pieces/pawn.rs
  src/popups.rs
  src/ui.rs
  src/utils.rs
Labels: enhancement

#97 fix: bot promotion using UCI standard
  src/board.rs
Labels: bug

#109 fix: en passant make sure we eat the piece
  src/board.rs
  tests/pieces/pawn.rs
Labels: bug

#85 Mouse click
  src/board.rs
  src/handler.rs
  src/main.rs
  src/popups.rs
  src/ui.rs
Labels: enhancement

#84 Bug fix: Bot move freezes player move
  src/board.rs
  src/main.rs
Labels: bug

#114 refactor: split code
  src/app.rs
  src/board.rs
  src/constants.rs
  src/game_logic/board.rs
  src/game_logic/bot.rs
  src/game_logic/coord.rs
  src/game_logic/game.rs
  src/game_logic/game_board.rs
  src/game_logic/mod.rs
  src/game_logic/ui.rs
  src/handler.rs
  src/lib.rs
  src/main.rs
  src/pieces/bishop.rs
  src/pieces/king.rs
  src/pieces/knight.rs
  src/pieces/mod.rs
  src/pieces/pawn.rs
  src/pieces/queen.rs
  src/pieces/rook.rs
  src/ui/main_ui.rs
  src/ui/mod.rs
  src/ui/popups.rs
  src/ui/tui.rs
  src/utils.rs
  tests/checkmates.rs
  tests/draws.rs
  tests/fen.rs
  tests/pieces/bishop.rs
  tests/pieces/king.rs
  tests/pieces/knight.rs
  tests/pieces/pawn.rs
  tests/pieces/queen.rs
  tests/pieces/rook.rs
  tests/promotions.rs
  website/docs/Code Architecture/Game.md
  website/docs/Code Architecture/intro.md
  website/docs/logo.png
  website/src/css/custom.css
  website/static/img/logo.png
  website/yarn.lock
Labels: documentation, refactor
